on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: 📄 Create .env file
        run: |
          echo "NEXT_PUBLIC_ANIME_API_URL=${{ secrets.NEXT_PUBLIC_ANIME_API_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "GITHUB_CLIENTID=${{ secrets.SECRET_GITHUB_CLIENTID }}" >> .env
          echo "GITHUB_SECRET=${{ secrets.SECRET_GITHUB_SECRET }}" >> .env
          echo "GOOGLE_CLIENTID=${{ secrets.GOOGLE_CLIENTID }}" >> .env
          echo "GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}" >> .env

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Prisma migrate
        run: npx prisma migrate deploy

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
